model_type: "uninavid"
model_path: "VLN-CE/models/uninavid_weights/vicuna-7b-v1.5"
vision_tower: "VLN-CE/models/uninavid_weights/eva_vit_g.pth"
image_processor: "rlinf/models/embodiment/uninavid/processor/clip-patch14-224"
version: "imgsp_v1"
precision: "bf16"
is_lora: false
mm_projector_type: "mlp2x_gelu"
mm_vision_select_layer: -2
mm_use_im_start_end: false
mm_use_im_patch_token: false
image_aspect_ratio: "pad"
video_fps: 1
compress_type: "grid:2"
tune_vision_encoder: false
model_max_length: 2048
add_value_head: false
load_to_device: true
